### ISSUE TITLE
Phase 1 feedback

### ISSUE THREAD

**Issue by sim642** [sim642/shy#31]
- [x] `UserPresentableException` on üsna kohmakas konstruktsioon. exceptionid on üldiselt ikka kõik koodi jaoks, mitte lõppkasutaja jaoks mõeldud. küll aga võiks agaramalt kasutada enda `RuntimeException`i subclasse. siis saaks tekitada klassi (n-ö _exception mapper_), mis oskab vastavalt exceptioni tüübile sellest kasutajale sobiliku _error message_ vorpida (1980a92edd83f4f0ba77bab294d642a6d93ae954)
- [x] `SuperCommand#execute` (muutja `Map<> subcommands`) `subCommands.keySet().contains` asemel võiks kasutada `subCommands.containsKey` (4087df770036b995e9dc863af2769c1215fdb458)
- [x] `Repository#fullFilePath` `new File(this.rootDirectory.getPath(), ".shy/commit/")` lendab ilmselt windowsi peal õhku - kaldkriipsude asemel kasuta `File` konstruktorit või `Paths.get` (#29)
- [x] `Repository` meetodid ei kontrolli `File` `mkdir`, `mkdirs`, `createNewFile` _return value_'t. Need on vastikud meetodid, mis ei viska exceptionit, kui nad oma tööga hakkama ei saa. (#29)
- [x] `Repository#commit`, `#newEmpty` `teeOutputStream` peaks _try-with-resources_ sees olema (303f96ae0364feacd2d4458bcdbc8381631a9f01)
- [x] `Tree.Builder` `FileInputStream` peaks _try-with-resources_ sees olema (303f96ae0364feacd2d4458bcdbc8381631a9f01)
- [x] `Hash(MessageDigest md)` võiks parameetriks `byte[]` võtta - praegu mõttetu `MessageDigest` _dependency_ (0b19fc07df032fa9be7ffe89a2ead0c3da6d06be)
- [x] `Json#write` `<T>` tüübiparameeter on üleliigne: `write(OutputStream os, Object object)` toimiks sama hästi (2b445c82a0bb2e7a9f4568b8f6d6c7de95b2a06e)
- [x] `Jsonable` klass on väga kahtlane. Superclasse saab olla ainult üks.. tavaliselt superclass määrab subclassi olemuse suuremas plaanis. Antud juhul `Jsonable` on ainult üks pisike aspeks subclassi olemusest. Soovitan teha `Jsonable` _interface_'ks ja `write` _interface_'i (`default`?) meetodiks. `Inputify` tundub ebavajalik. Seda kasutatakse ainult `DataStorage#add` meetodis, aga sellele saaks teha vabalt _overload_, mis võtab `Jsonable` parameetriks ja kasutab `write`:
  
  ``` java
  ByteArrayOutputStream baos = new ByteArrayOutputStream();
  DigestOutputStream dis = new DigestOutputStream(baos, md);
  jsonable.write(dis);
  ```
  
  (ae2bb1eca5e29d2a756861cf36db8093203622f1)
- [x] `DataStorage#getUnchecked` võiks protected olla (7770d99808e1ec2d028145e5f8b7de2f0aa4f948)
- [x] `DataStorage#get` ei pane `DigestInputStream` kinni (1633873c7e6cb1830e2b56e05e2593322d8c0aae)
- [x] `Util#ensurePath` võiks nime järgi olla `void` ja visata exceptioni, kui feilib (#29)
